# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Make API request to update rotation when any rotation is changed

on:
  push:
    branches:
      - 'main'
    paths:
      - '**.txt'

jobs:
  deployment:
    runs-on: ubuntu-20.04  # windows-latest || macos-latest
    environment: production
    strategy:
      matrix:
        node-version: [16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
    name: Get all changed files and make API request
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # OR "2" -> To retrieve the preceding commit.

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v40.1.0

      - name: Setup Node JS
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - run: npm install axios
      - name: Make request to update file
        uses: actions/github-script@v6
        with:
          script: |
            const axios = require('axios');
            const endpoint = 'https://pokeapi.co/api/v2/pokemon/ditto';
            const res = await axios.get(endpoint);
            console.log('${{ steps.changed-files.outputs.all_changed_files }}');
            console.log(res.status);
            console.log('${{ secrets.AUTH_TOKEN }}');